# Generated by Django 3.2.10 on 2022-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Not Specified', unique=True)),
                ('ticker', models.CharField(default='Not Specified', max_length=254, unique=True)),
                ('contract', models.TextField(default='Not Specified')),
                ('abi', models.TextField(default='Not Specified')),
                ('official_site', models.TextField(default='Not Specified')),
            ],
            options={
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
